name: djangoPlayground

dependencies:
  - python=3.8.1
  - psycopg2=2.8.4
  - pip:
    - Django==3.0.2
    - flake8==3.7.9
    - djangorestframework==3.11.0
    - markdown==3.1.1
    - django-filter==2.2.0
    - djangorestframework_simplejwt==4.4.0
    - coreapi==2.3.3
    - gunicorn==20.0.4
    - Pillow==7.0.0
    - django-cors-headers==3.2.1
    - weasyprint
    - django-weasyprint==0.5.5
